### CSRF
GET http://127.0.0.1:8080/api/v1/csrf
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-Access-Token: 4c4282f943f38ac355de

###SIGNUP
POST http://127.0.0.1:8080/api/v1/auth/register
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-CSRF-Token: 28036f650a241aa66e4a
# X-Access-Token: d69fb9ee7a9459b1d4c6
Content-Type: application/json

{
    "email":"jiajun@deriv.com"
}

###SECURE WORD
POST http://192.168.18.64:8080/api/v1/auth/secure-word
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-CSRF-Token: 9a5ca9e8db923bd5019c
# X-Access-Token: d69fb9ee7a9459b1d4c6
Content-Type: application/json

{
    "username":"junchan@derifdfsddv.com"
}

### LOGIN
POST http://192.168.18.64:8080/api/v1/auth/login
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-CSRF-Token: 79df84ae13381f5c383b
Content-Type: application/json

{
    "username":"junchan@deriv.com",
    "password":"chicken"
}

### Finish signup
POST http://127.0.0.1:8080/api/v1/auth/finalize-registration
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-CSRF-Token: 7f209f1b49a90020ad8c
Content-Type: application/json

{
  "verification_code": "047045da4b9fb356c2b6",
  "first_name": "Jia Jun",
  "last_name": "Ngeo",
  "username": "hana",
  "password": "chicken",
  "password_again": "chicken",
  "gender": "male",
  "telephone_number":"+601234567890",
  "secure_word": "ranndom"
}

### Profile
GET http://192.168.18.64:8080/api/v1/whoami
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-Access-Token: 742d23fcddf8fc6e2853
X-CSRF-Token: 3233f7a48f2914eaa797

###
PATCH http://192.168.18.64:8080/api/v1/whoami
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-Access-Token: d69fb9ee7a9459b1d4c6
X-CSRF-Token: f51374387000bdd1daad
Content-Type: application/json

{
    "birthday":"2000-09-09"
}

### Logout
GET http://192.168.18.64:8080/api/v1/auth/revoke
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
X-Access-Token: 742d23fcddf8fc6e2853

### Products
GET http://192.168.18.64:8080/api/v1/product
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly

### Categories
GET http://192.168.18.64:8080/api/v1/product/categories
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly

### Products
GET http://127.0.0.1:8080/api/v1/product/shoes
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly

###Stock
GET http://192.168.18.64:8080/api/v1/product/stocks/20
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly

### add product to cart
PATCH http://127.0.0.1:8080/api/v1/orders/cart
X-Access-Token: 4c4282f943f38ac355de
X-CSRF-Token: 95e2ea35cbab316bf5a8
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
Content-Type: application/json

[{"product_id":1,"quantity":3}]

### populate product to cart
POST  http://127.0.0.1:8080/api/v1/orders/cart/populate
X-Access-Token: 4c4282f943f38ac355de
X-CSRF-Token: feadd39bf5d08e9742fd
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
Content-Type: application/json

{"order_id":12004}

### checkout
POST http://127.0.0.1:8080/api/v1/orders/cart/checkout
X-Access-Token: 4c4282f943f38ac355de
X-CSRF-Token: 164f70df51ed3a135004
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
Content-Type: application/json

{
    "address":"a","residence":"b"
}

### checkout
GET http://127.0.0.1:8080/api/v1/orders/124
X-Access-Token: 4c4282f943f38ac355de
Cookie: session_id=s%3A46d1e344035e686847b8.naXDeacILTkWkLiOG99%2FF3JYLRlqz7S%2BgrS6gAQlAts; Path=/; HttpOnly
